<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>poll</AssemblyName>
    <RootNamespace>VotingPlugin</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EXILED" Version="9.0.0-beta.2" />
  </ItemGroup>

</Project>
